object LibraryDependency {
    const val KOTLIN = "org.jetbrains.kotlin:kotlin-stdlib:${LibraryVersion.KOTLIN}"
    const val CORE_KTX = "androidx.core:core-ktx:${LibraryVersion.CORE_KTX}"
    const val APP_COMPAT = "androidx.appcompat:appcompat:${LibraryVersion.APP_COMPAT}"
    const val MATERIAL = "com.google.android.material:material:${LibraryVersion.MATERIAL}"
    const val RETROFIT = "com.squareup.retrofit2:retrofit:${LibraryVersion.RETROFIT}"
    const val RETROFIT_COROUTINES_ADAPTER = "com.jakewharton.retrofit:retrofit2-kotlin-coroutines-adapter:${LibraryVersion.RETROFIT_COROUTINES_ADAPTER}"
    const val RETROFIT_GSON_CONVERTER = "com.squareup.retrofit2:converter-gson:${LibraryVersion.RETROFIT}"
    const val COROUTINES = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${LibraryVersion.COROUTINES}"
    const val COROUTINES_ANDROID = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${LibraryVersion.COROUTINES}"
    const val LOGGING_INTERCEPTOR = "com.squareup.okhttp3:logging-interceptor:${LibraryVersion.LOGGING_INTERCEPTOR}"
    const val CARD_VIEW = "androidx.cardview:cardview:${LibraryVersion.CARD_VIEW}"
    const val VIEW_MODEL_SCOPE = "androidx.lifecycle:lifecycle-viewmodel-ktx:${LibraryVersion.VIEW_MODEL_SCOPE}"
    const val JUNIT = "org.junit.jupiter:junit-jupiter:${LibraryVersion.JUNIT}"
    const val JUNIT_API = "org.junit.jupiter:junit-jupiter-api:${LibraryVersion.JUNIT}"
    const val JUNIT_ENGINE = "org.junit.jupiter:junit-jupiter-engine:${LibraryVersion.JUNIT}"
    const val FEST_ASSERT_CORE = "org.easytesting:fest-assert-core:${LibraryVersion.FEST_ASSERT_CORE}"
    const val MOCKK = "io.mockk:mockk:${LibraryVersion.MOCKK}"
    const val DAGGER = "com.google.dagger:dagger:${LibraryVersion.DAGGER}"
    const val DAGGER_ANDROID = "com.google.dagger:dagger-android:${LibraryVersion.DAGGER}"
    const val DAGGER_ANDROID_SUPPORT = "com.google.dagger:dagger-android-support:${LibraryVersion.DAGGER}"
    const val DAGGER_COMPILER = "com.google.dagger:dagger-compiler:${LibraryVersion.DAGGER}"
    const val DAGGER_PROCESSOR = "com.google.dagger:dagger-android-processor:${LibraryVersion.DAGGER}"}

object LibraryVersion {
    const val KOTLIN = "1.5.0"
    const val CORE_KTX = "1.5.0"
    const val APP_COMPAT = "1.3.0"
    const val MATERIAL = "1.3.0"
    const val RETROFIT = "2.9.0"
    const val COROUTINES = "1.5.0"
    const val RETROFIT_COROUTINES_ADAPTER = "0.9.2"
    const val LOGGING_INTERCEPTOR = "4.9.1"
    const val CARD_VIEW = "1.0.0"
    const val VIEW_MODEL_SCOPE = "2.3.1"
    const val JUNIT = "5.8.0"
    const val MOCKK = "1.12.0"
    const val DAGGER = "2.38.1"
    const val FEST_ASSERT_CORE = "2.0M10"
}